project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - "!practice/"
    - "!unusedCode.qmd"

#server:
#  type: shiny

#notebook-view:
#  - notebook: pythonWorkflow.qmd
#    title: "Python Workflow"
   # url: notebooks/pythonWorkflow.qmd
engine: knitr


format:
  html:
    embed-resources: true
    toc: true
    toc-location: left
    #comments:
#      hypothesis:
#        theme: clean
#        openSidebar: false
    theme:
       - darkly
       - 'scss/main.scss'


website:
  title: "TruckerWeather"
  #navbar:
  # left:
  #    - href: index.qmd
  ##      text: Home
   #   - about.qmd

execute:
  freeze: auto
  
layout: article
editor: visual


