project:
  type: website
  render: 
    - index.qmd
    - "!practice/"

website:
  title: "TruckerWeather"
  #navbar:
  # left:
  #    - href: index.qmd
  ##      text: Home
   #   - about.qmd

engine: knitr
execute:
  freeze: auto
  
layout: article
editor: visual

format:
  html:
    comments:
      hypothesis:
        theme: clean
        openSidebar: false
    theme:
       - darkly
       - 'scss/main.scss'

